/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui.game.Components;

import client.ClientMain;
import java.awt.Color;
import java.awt.event.ComponentListener;
import java.net.URL;
import javax.swing.*;
import pt.up.fe.lpro1613.sharedlib.utils.Coord;

/**
 *
 * @author luisp
 */
public final class Block extends javax.swing.JPanel {

    /**
     * Creates new form Block
     * @param coordinates where this block is in the board
     */
    public Block(Coord coordinates) {
        initComponents();
        this.coordinates = coordinates;
    }
    
    private final Icon redCrossIcon = new ImageIcon(getClass().getResource("/client/ui/Images/redCross.png"));
    private final Icon blueDiamondIcon = new ImageIcon(getClass().getResource("/client/ui/Images/blueDiamond.png"));
    private final Icon greyCircleIcon = new ImageIcon(getClass().getResource("/client/ui/Images/greyCircle.png"));
    
    private boolean initialized = false;
    
    private void initializeAfterNetbeansRender()
    {
        if(initialized)
            return;
        initialized = true;

        ComponentListener cl = ClientMain.mainFrame.imageResizer;
        
        ComponentListener[] listeners = jLabel1.getComponentListeners().clone();
        for(ComponentListener _cl : listeners)
            if(_cl == cl)
            {
                jLabel1.removeComponentListener(_cl);
                break;
            }
        
        jLabel1.addComponentListener(cl);
    }
    
    public void setIcon(Icon icon)
    {
        initializeAfterNetbeansRender();
        
        removeAll();
        
        jLabel1.setIcon(icon);
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(SwingConstants.CENTER);
    }
    
    /**
     * Sets the background color of this Block
     * @param _c new color for this Block. If null, the default Color will be used, aka resets the Block's Color
     */
    public void setColor(java.awt.Color _c)
    {
        Color color;
        if(_c == null)
        {
            color = new Color(240,240,240);
        }
        else
        {
            color = new Color(143,143,143);
        }
        setBackground(color);
        jLabel1.setBackground(color);
    }
    
    public final Coord coordinates;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
