/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui.game.Components;

import client.ClientMain;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import pt.up.fe.lpro1613.sharedlib.utils.*;

/**
 *
 * @author luisp
 */
public final class Block extends javax.swing.JPanel {

    /**
     * Creates new form Block
     * @param coordinates where this block is in the board 
     */
    public Block(Coord coordinates) {
        this(coordinates,null);
    }
    
    /**
     * Creates new form Block
     * @param coordinates where this block is in the board
     * @param text Text to be set. If text is not null, no icon can be set.
     */
    public Block(Coord coordinates, String text) {
        initComponents();
        this.coordinates = coordinates;
        sanityCheck();
        
        this.text = text;
        if(text != null)    //label
        {
            jLabel1.setText(text);
        }
        else    //button
        {
            addMouseListener(clickListener);
            jLabel1.addMouseListener(clickListener);
            setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        }
    }
    
    /**
     * not null if this Block is a line/row label
     */
    public final String text;
    
    private void sanityCheck()
    {
        boolean containsLabel = false;
        for(Component _c : getComponents())
        {
            if(_c == jLabel1)
            {
                containsLabel = true;
                break;
            }
        }
        if(!containsLabel)
            add(jLabel1);
        jLabel1.setVisible(true);
        jLabel1.setOpaque(true);
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(SwingConstants.CENTER);
    }
    
    private final MouseListener clickListener = new MouseListener() {
        private boolean prev = false;
        @Override
        public void mouseClicked(MouseEvent e) {
            
        }

        @Override
        public void mousePressed(MouseEvent e) {
            /*setIcon(prev ? redCrossIcon : null);
            prev = !prev;*/
            setIcon(redCrossIcon);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            //System.out.println("released");
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            //System.out.println("entered");
            setColor(new Color(255, 0, 0));
        }

        @Override
        public void mouseExited(MouseEvent e) {
            //System.out.println("exited");
            setColor(Color.black);
        }
    };
    
    public static final Icon redCrossIcon = new ImageIcon(Block.class.getResource("/client/ui/Images/redCross.png"));
    public static final Icon blueDiamondIcon = new ImageIcon(Block.class.getResource("/client/ui/Images/blueDiamond.png"));
    public static final Icon greyCircleIcon = new ImageIcon(Block.class.getResource("/client/ui/Images/greyCircle.png"));
    
    private boolean resizable = false;
    
    private void setImageResizer()
    {
        if(resizable)
            return;
        resizable = true;

        ComponentListener cl = ClientMain.mainFrame.imageResizer;
        
        jLabel1.addComponentListener(cl);
    }
    
    public void setIcon(Icon icon)
    {
        if(text != null)
            return;
        
        setImageResizer();
        
        jLabel1.removeAll();
        
        jLabel1.setIcon(icon);
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(SwingConstants.CENTER);
        
        //To trigger the image resizing
        jLabel1.setVisible(false);
        jLabel1.setVisible(true);
    }
    
    /**
     * Sets the background color of this Block
     * @param _c new color for this Block. If null, the default Color will be used, aka resets the Block's Color
     */
    public void setColor(java.awt.Color _c)
    {
        Color color;
        if(_c == null)
        {
            color = new Color(240,240,240);
        }
        else
        {
            color = _c;
            //color = new Color(143,143,143);
        }
        setBackground(color);
        jLabel1.setBackground(color);
    }
    
    public final Coord coordinates;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
