/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui.game.Components;

import java.awt.*;
import java.util.Collections;
import static pt.up.fe.lpro1613.sharedlib.constants.BoardK.*;
import pt.up.fe.lpro1613.sharedlib.utils.Coord;
import pt.up.fe.lpro1613.sharedlib.utils.Matrix;

/**
 *
 * @author luisp
 */
public final class Board extends javax.swing.JPanel {

    public Board() {
        initComponents();
        setLayout(new GridLayout(BOARD_SIZE,BOARD_SIZE));
        
        final Matrix<Block> grid = new Matrix<>(BOARD_SIZE,BOARD_SIZE,null);
        for(int i = 0; i < BOARD_SIZE*BOARD_SIZE ; i++){
            Coord coord = new Coord(i%BOARD_SIZE,(int)i/BOARD_SIZE);
            Block block = new Block(coord);
            add(block); //puts the Block in the grid
            grid.set(coord,block);
        }
        this.grid = grid.getUnmodifiableMatrix();
    }

    final Matrix<Block> grid;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
