/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui.game.Components;

import java.awt.BorderLayout;
import sharedlib.structs.UIInfo;

/**
 *
 * @author luisp
 */
public class BoardContainer extends javax.swing.JPanel {

    /**
     * Creates new form BoardContainer
     */
    public BoardContainer() {
        initComponents();
        this.left = board.left;
        shipsPreview = left ? new ShipsPreviewLeft() : new ShipsPreviewRight();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board = new client.ui.game.Components.Board();

        setLayout(new java.awt.BorderLayout());
        add(board, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public final boolean left;
    
    private boolean waiting;
    public void setOpponentWaiting(boolean waiting)
    {
        this.waiting = waiting;
        if(waiting && !(board instanceof WaitingOnOpponentPanel))
        {
            board = new WaitingOnOpponentPanel(board.left);
            shipsPreview = null;
            repaintBoard();
        }
        else if(!waiting && !(board instanceof Board))
        {
            board = new Board(left);
            shipsPreview = left ? new ShipsPreviewLeft() : new ShipsPreviewRight();
            repaintBoard();
        }
    }
    
    private SuperBoard previousBoard = null;
    
    private void repaintBoard()
    {
        this.removeAll();
        this.add(board,BorderLayout.CENTER);
        if(shipsPreview != null)
            this.add(shipsPreview,BorderLayout.PAGE_END);
        previousBoard = board;
    }
    
    private ShipsPreview shipsPreview;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private client.ui.game.Components.SuperBoard board;
    // End of variables declaration//GEN-END:variables

    public void updateBoard(UIInfo info) {
        board.update(info);
    }
}
