/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui.game.Components;

import client.ClientMain;
import client.logic.*;
import java.util.logging.*;
import pt.up.fe.lpro1613.sharedlib.exceptions.*;

/**
 *
 * @author luisp
 */
public class GameChat extends javax.swing.JPanel {

    /**
     * Creates new form GameChat
     */
    public GameChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollableGameChat = new javax.swing.JScrollPane();
        gameChatTextAre = new javax.swing.JTextArea();
        gameChatSendMessageField = new javax.swing.JTextField();
        gameChatSendButton = new javax.swing.JButton();

        gameChatTextAre.setEditable(false);
        gameChatTextAre.setColumns(20);
        gameChatTextAre.setRows(5);
        scrollableGameChat.setViewportView(gameChatTextAre);

        gameChatSendMessageField.setToolTipText("Press enter to send message");
        gameChatSendMessageField.setMaximumSize(new java.awt.Dimension(2147483647, 26));

        gameChatSendButton.setText("Send message");
        gameChatSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameChatSendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollableGameChat, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameChatSendMessageField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameChatSendButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollableGameChat, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameChatSendMessageField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameChatSendButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gameChatSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameChatSendButtonActionPerformed
        try {
            GlobalChatC.sendGlobalMessage(gameChatSendMessageField.getText());
            gameChatSendMessageField.setText("");
        }
        catch (UserMessageException ex) {
            Logger.getLogger(GameChat.class.getName()).log(Level.SEVERE, null, ex);
            ClientMain.showError(ex.getMessage());
        }
    }//GEN-LAST:event_gameChatSendButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gameChatSendButton;
    private javax.swing.JTextField gameChatSendMessageField;
    private javax.swing.JTextArea gameChatTextAre;
    private javax.swing.JScrollPane scrollableGameChat;
    // End of variables declaration//GEN-END:variables
}
