/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui.game.Components;

import client.logic.*;

/**
 *
 * @author luisp
 */
public class GameChat extends javax.swing.JPanel {

    /**
     * Creates new form GameChat
     */
    public GameChat() {
        initComponents();
        chatPane.setContentType("text/html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameChatSendMessageField = new javax.swing.JTextField();
        gameChatSendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatPane = new javax.swing.JTextPane();

        gameChatSendMessageField.setToolTipText("Press enter to send message");
        gameChatSendMessageField.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        gameChatSendMessageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameChatSendMessageFieldActionPerformed(evt);
            }
        });

        gameChatSendButton.setText("Send");
        gameChatSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameChatSendButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(chatPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameChatSendMessageField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameChatSendButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameChatSendMessageField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameChatSendButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gameChatSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameChatSendButtonActionPerformed
        if (gameChatSendMessageField.getText().isEmpty()) {
            return;
        }

        GameChatC.sendGameMessage(gameChatSendMessageField.getText());
        gameChatSendMessageField.setText("");
    }//GEN-LAST:event_gameChatSendButtonActionPerformed

    private void gameChatSendMessageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameChatSendMessageFieldActionPerformed
        gameChatSendButtonActionPerformed(evt);
    }//GEN-LAST:event_gameChatSendMessageFieldActionPerformed

    public void refreshGameMessages() {
        chatPane.setText(GameChatC.messagesHTML());
        chatPane.setCaretPosition(chatPane.getDocument().getLength()); // Scroll to bottom
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane chatPane;
    private javax.swing.JButton gameChatSendButton;
    private javax.swing.JTextField gameChatSendMessageField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
