/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui.game.Components;

import client.logic.GameC;
import static client.other.HTMLEscaping.escapeHTML;

/**
 *
 * @author luisp
 */
public class TopBar extends javax.swing.JPanel {

    /**
     * Creates new form AdvertisementPanel
     */
    public TopBar() {
        initComponents();
        reloadUI();
    }

    private final String SEPARATOR = "&emsp;&emsp;VS&emsp;&emsp;";
    private String player1 = "?????";
    private String player2 = "?????";

    private boolean playerTurn;
    private boolean opponentTurn;

    private String getHTMLString() {
        StringBuilder sb = new StringBuilder();
        sb.append("<html><body>");
        if (playerTurn) {
            sb.append("<a style=\"color: #ffffff; background-color: #000000\">&ensp;");
            sb.append(escapeHTML(player1));
            sb.append("&ensp;</a>");
        }
        else {
            sb.append(escapeHTML(player1));
        }
        sb.append(SEPARATOR);
        if (opponentTurn) {
            sb.append("<a style=\"color: #ffffff; background-color: #000000\">&ensp;");
            sb.append(escapeHTML(player2));
            sb.append("&ensp;</a>");
        }
        else {
            sb.append(escapeHTML(player2));
        }
        sb.append("</body></html>");
        return sb.toString();
    }

    private void reloadUI() {
        opponentsLabel.setText(getHTMLString());
    }

    public final void setTurn(boolean playerTurn, boolean opponentTurn) {
        this.playerTurn = playerTurn;
        this.opponentTurn = opponentTurn;
        reloadUI();
    }

    public final void setFirstPlayer(String player1) {
        this.player1 = player1;
        reloadUI();
    }

    public final void setSecondPlayer(String player2) {
        this.player2 = player2;
        reloadUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topGamePanel = new javax.swing.JLayeredPane();
        opponentsLabel = new javax.swing.JLabel();
        closeBttn = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        topGamePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topGamePanel.setMinimumSize(new java.awt.Dimension(200, 60));

        opponentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        closeBttn.setText("Close");
        closeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBttnActionPerformed(evt);
            }
        });

        topGamePanel.setLayer(opponentsLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        topGamePanel.setLayer(closeBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout topGamePanelLayout = new javax.swing.GroupLayout(topGamePanel);
        topGamePanel.setLayout(topGamePanelLayout);
        topGamePanelLayout.setHorizontalGroup(
            topGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topGamePanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(opponentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBttn)
                .addContainerGap())
        );
        topGamePanelLayout.setVerticalGroup(
            topGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topGamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeBttn)
                    .addComponent(opponentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBttnActionPerformed
        GameC.closeGame();
    }//GEN-LAST:event_closeBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBttn;
    private javax.swing.JLabel opponentsLabel;
    private javax.swing.JLayeredPane topGamePanel;
    // End of variables declaration//GEN-END:variables
}
