/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui;

/**
 *
 * @author luisp
 */
public class AdvertisementPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdvertisementPanel
     */
    public AdvertisementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        advertisementPanel = new javax.swing.JLayeredPane();
        advertisementImage = new javax.swing.JLabel();

        advertisementPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Advertisement"));
        advertisementPanel.setMinimumSize(new java.awt.Dimension(200, 60));

        advertisementImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        advertisementImage.setText("ADVERTISEMENT BANNER");
        advertisementImage.setMinimumSize(new java.awt.Dimension(0, 0));

        advertisementPanel.setLayer(advertisementImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout advertisementPanelLayout = new javax.swing.GroupLayout(advertisementPanel);
        advertisementPanel.setLayout(advertisementPanelLayout);
        advertisementPanelLayout.setHorizontalGroup(
            advertisementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advertisementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advertisementImage, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        advertisementPanelLayout.setVerticalGroup(
            advertisementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(advertisementImage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advertisementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advertisementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertisementImage;
    private javax.swing.JLayeredPane advertisementPanel;
    // End of variables declaration//GEN-END:variables
}
