/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui;

import client.ClientMain;
import javax.swing.*;

/**
 *
 * @author luisp
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public JPanel getLoginPanel()
    {
        return loginPanel2;
    }
    
    public void changeToPanel(javax.swing.JComponent panel)
    {
        getContentPane().removeAll();
        getContentPane().add(advertisementPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel2 = new client.ui.LoginPanel();
        advertisementPanel1 = new client.ui.AdvertisementPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().add(loginPanel2, java.awt.BorderLayout.CENTER);
        getContentPane().add(advertisementPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private client.ui.AdvertisementPanel advertisementPanel1;
    private client.ui.LoginPanel loginPanel2;
    // End of variables declaration//GEN-END:variables
}
